PYTHON 			= python3
PIP				= pip3
UIC				= pyside6-uic

VENV 			= .venv
SRC_UI_FILES 	= $(wildcard stfed/view/*.ui)
UI_PY_FILES		= $(subst view/,view/autogenerated/Ui_,$(subst .ui,.py,$(SRC_UI_FILES)))

setup:  $(UI_PY_FILES) | $(VENV)

run: $(UI_PY_FILES) 
	. $(VENV)/bin/activate && $(PYTHON) -m stfed

clean:
	rm -rf $(VENV)

.PHONY = setup clean run

$(VENV): requirements.txt
	$(PYTHON) -m venv $(VENV) \
		&& . $(VENV)/bin/activate \
		&& $(PIP) install -r requirements.txt

stfed/view/autogenerated/Ui_%.py: stfed/view/%.ui
	$(UIC) $< -o $@
