from PySide6 import QtCore, QtGui, QtWidgets
import PySide6.QtGui

import stfed.consts
from stfed.view.autogenerated.Ui_AboutWindow import Ui_AboutWindow


class AboutWindow(QtWidgets.QWidget, Ui_AboutWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        # sizePolicy.xxxPolicy.Fixed apparently does nothing
        self.setFixedSize(self.size())
        self.about_label.setText(self.about_label.text().replace("{STFED_VERSION}", stfed.consts.STFED_VERSION))

    def keyPressEvent(self, event: QtGui.QKeyEvent) -> None:
        if event.key() == QtGui.Qt.Key.Key_Escape:
            self.close()
            return
        return super().keyPressEvent(event)