from PySide6 import QtCore, QtGui, QtWidgets

import stfed.consts
import stfed.services.platform_specific
from stfed.view.autogenerated.Ui_AboutWindow import Ui_AboutWindow


class AboutWindow(QtWidgets.QWidget, Ui_AboutWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.setFixedSize(self.size())
        self.about_label.setText(self.about_label.text().replace("{STFED_VERSION}", stfed.consts.STFED_VERSION))
        self.about_label.setOpenExternalLinks(True)
        self.license_button.clicked.connect(stfed.services.platform_specific.show_license)


    def keyPressEvent(self, event: QtGui.QKeyEvent) -> None:
        if event.key() == QtGui.Qt.Key.Key_Escape:
            self.close()
            return
        return super().keyPressEvent(event)