from PySide6 import QtCore, QtGui, QtWidgets

import stfed.services.hexdump
from stfed.view.autogenerated.Ui_DefaultResourcePreview import Ui_DefaultResourcePreview


class DefaultResourcePreview(QtWidgets.QWidget, Ui_DefaultResourcePreview):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def set_model(self, resource):
        data = resource.data()
        formatted = stfed.services.hexdump.display_hexdump(data)
        self.plain_text_edit.setPlainText(formatted)

